chore(deps): update dependency commander to v13 (#38)
This PR contains the following updates:

| Package | Type | Update | Change |
|---|---|---|---|
| [commander](https://github.com/tj/commander.js) | devDependencies | major | [`12.1.0` -> `13.0.0`](https://renovatebot.com/diffs/npm/commander/12.1.0/13.0.0) |

---

### Release Notes

<details>
<summary>tj/commander.js (commander)</summary>

### [`v13.0.0`](https://github.com/tj/commander.js/blob/HEAD/CHANGELOG.md#1300-2024-12-30)

[Compare Source](https://github.com/tj/commander.js/compare/v12.1.0...v13.0.0)

##### Added

-   support multiple calls to `.parse()` with default settings (\[[#&#8203;2299](https://github.com/tj/commander.js/issues/2299)])
-   add `.saveStateBeforeParse()` and `.restoreStateBeforeParse()` for use by subclasses (\[[#&#8203;2299](https://github.com/tj/commander.js/issues/2299)])
-   style routines like `styleTitle()` to add color to help using `.configureHelp()` or Help subclass (\[[#&#8203;2251](https://github.com/tj/commander.js/issues/2251)])
-   color related support in `.configureOutput()` for `getOutHasColors()`, `getErrHasColors()`, and `stripColor()` (\[[#&#8203;2251](https://github.com/tj/commander.js/issues/2251)])
-   Help property for `minWidthToWrap` (\[[#&#8203;2251](https://github.com/tj/commander.js/issues/2251)])
-   Help methods for `displayWidth()`, `boxWrap()`, `preformatted()` et al (\[[#&#8203;2251](https://github.com/tj/commander.js/issues/2251)])

##### Changed

-   *Breaking*: excess command-arguments cause an error by default, see migration tips (\[[#&#8203;2223](https://github.com/tj/commander.js/issues/2223)])
-   *Breaking*: throw during Option construction for unsupported option flags, like multiple characters after single `-` (\[[#&#8203;2270](https://github.com/tj/commander.js/issues/2270)])
-   *Breaking*: throw on multiple calls to `.parse()` if `storeOptionsAsProperties: true` (\[[#&#8203;2299](https://github.com/tj/commander.js/issues/2299)])
-   TypeScript: include implicit `this` in parameters for action handler callback (\[[#&#8203;2197](https://github.com/tj/commander.js/issues/2197)])

##### Deleted

-   *Breaking*: `Help.wrap()` refactored into `formatItem()` and `boxWrap()` (\[[#&#8203;2251](https://github.com/tj/commander.js/issues/2251)])

##### Migration Tips

**Excess command-arguments**

It is now an error for the user to specify more command-arguments than are expected. (`allowExcessArguments` is now false by default.)

Old code:

```js
program.option('-p, --port <number>', 'port number');
program.action((options) => {
  console.log(program.args);
});
```

Now shows an error:

```console
$ node example.js a b c
error: too many arguments. Expected 0 arguments but got 3.
```

You can declare the expected arguments. The help will then be more accurate too. Note that declaring
new arguments will change what is passed to the action handler.

```js
program.option('-p, --port <number>', 'port number');
program.argument('[args...]', 'remote command and arguments'); // expecting zero or more arguments
program.action((args, options) => {
  console.log(args);
});
```

Or you could suppress the error, useful for minimising changes in legacy code.

```js
program.option('-p, --port', 'port number');
program.allowExcessArguments();
program.action((options) => {
  console.log(program.args);
});
```

</details>

---

### Configuration

📅 **Schedule**: Branch creation - At any time (no schedule defined), Automerge - At any time (no schedule defined).

🚦 **Automerge**: Disabled by config. Please merge this manually once you are satisfied.

♻ **Rebasing**: Whenever PR becomes conflicted, or you tick the rebase/retry checkbox.

🔕 **Ignore**: Close this PR and you won't be reminded about this update again.

---

 - [ ] <!-- rebase-check -->If you want to rebase/retry this PR, check this box

---

This PR has been generated by [Renovate Bot](https://github.com/renovatebot/renovate).
<!--renovate-debug:eyJjcmVhdGVkSW5WZXIiOiIzOS44NC4wIiwidXBkYXRlZEluVmVyIjoiMzkuODQuMCIsInRhcmdldEJyYW5jaCI6Im1haW4iLCJsYWJlbHMiOltdfQ==-->

Reviewed-on: https://git.justinelmore.dev/jelmore1674/build-changelog/pulls/38
Reviewed-by: Justin Elmore <jelmore1674@noreply.justinelmore.dev>
Co-authored-by: Renovate Bot <renovate-bot@forgejo.justinelmore.dev>
Co-committed-by: Renovate Bot <renovate-bot@forgejo.justinelmore.dev>